import pandas as pd
file = "Pokédex_Info.xlsx"
pokedex = pd.read_excel(file)

print("Welcome to the Pokédex!")
user = float(input(":_ "))


found_pokemon = pokedex[pokedex["National\nDex"] == user]
pokemon = found_pokemon.to_dict()

print(pokemon)

# print(pokedex["National\nDex"][user_input])
# print(pokedex["Pokemon\nName"][user_input])
# print(pokedex["Type"][user_input])
# print(pokedex["HP"][user_input])
# print(pokedex["Attack"][user_input])
# print(pokedex["Defense"][user_input])
# print(pokedex["Special\nAttack"][user_input])
# print(pokedex["Special\nDefense"][user_input])
# print(pokedex["Speed"][user_input])
# print(pokedex["Total"][user_input])
# print(pokedex["Type I"][user_input])
# print(pokedex["Type II"][user_input])
# print(pokedex["Ability I"][user_input])
# print(pokedex["Ability II"][user_input])
# print(pokedex["Hidden Ability"][user_input])
# print(pokedex["Height (m)"][user_input])
# print(pokedex["Weight (lbs)"][user_input])
# print(pokedex["Weight (kg)"][user_input])
# print(pokedex["HP EVs"][user_input])
# print(pokedex["Attcak EVs"][user_input])
# print(pokedex["Defense EVs"][user_input])
# print(pokedex["Special Attack EVs"][user_input])
# print(pokedex["Special Defense EVs"][user_input])
# print(pokedex["Speed EVs"][user_input])
# print(pokedex["Experience\nValue"][user_input])
# print(pokedex["Catch Rate"][user_input])
# print(pokedex["Experience\nGrowth"][user_input])
# print(pokedex["Base Friendship"][user_input])
# print(pokedex["pokedex Color"][user_input])
# print(pokedex["Gender Ratio"][user_input])
# print(pokedex["Egg Cycles"][user_input])
# print(pokedex["Egg Group I"][user_input])
# print(pokedex["Egg Group II"][user_input])
# print(pokedex["Evolution\nMethod"][user_input])
