import pandas as pd
df = pd.read_excel(r"Pokédex_Info.xlsx")
Pokedex = df.to_dict()

print("Ready to use Pokédex!")
User_input = int(input(":_ "))
print(Pokedex["National\nDex"][User_input])
print(Pokedex["Pokemon\nName"][User_input])
print(Pokedex["Type"][User_input])
print(Pokedex["HP"][User_input])
print(Pokedex["Attack"][User_input])
print(Pokedex["Defense"][User_input])
print(Pokedex["Special\nAttack"][User_input])
print(Pokedex["Special\nDefense"][User_input])
print(Pokedex["Speed"][User_input])
print(Pokedex["Total"][User_input])
print(Pokedex["Type I"][User_input])
print(Pokedex["Type II"][User_input])
print(Pokedex["Ability I"][User_input])
print(Pokedex["Ability II"][User_input])
print(Pokedex["Hidden Ability"][User_input])
print(Pokedex["Height (m)"][User_input])
print(Pokedex["Weight (lbs)"][User_input])
print(Pokedex["Weight (kg)"][User_input])
print(Pokedex["HP EVs"][User_input])
print(Pokedex["Attcak EVs"][User_input])
print(Pokedex["Defense EVs"][User_input])
print(Pokedex["Special Attack EVs"][User_input])
print(Pokedex["Special Defense EVs"][User_input])
print(Pokedex["Speed EVs"][User_input])
print(Pokedex["Experience\nValue"][User_input])
print(Pokedex["Catch Rate"][User_input])
print(Pokedex["Experience\nGrowth"][User_input])
print(Pokedex["Base Friendship"][User_input])
print(Pokedex["Pokedex Color"][User_input])
print(Pokedex["Gender Ratio"][User_input])
print(Pokedex["Egg Cycles"][User_input])
print(Pokedex["Egg Group I"][User_input])
print(Pokedex["Egg Group II"][User_input])
print(Pokedex["Evolution\nMethod"][User_input])
